### ISSUE TITLE
ugly hamburger

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#110]
![screen shot 2016-09-07 at 3 55 59 pm](https://cloud.githubusercontent.com/assets/7727722/18328227/98bbc8d6-7513-11e6-9a79-ef3d3a6cfd34.png)
trash

**Comment by mikeyrayvon** [comment]
this actually looks fine on an **actual** phone so im closing this

**Comment by varffs** [comment]
but...
