### ISSUE TITLE
Programacion credits

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/estanciafemsa-mx#123]
Why are the credits in is own WYSWG? In the design old and new, looks like they are just part of the content.

**Comment by mikeyrayvon** [comment]
i talked to them about this. credits is its own wysiwyg

**Comment by mixcas** [comment]
Why did you close this? Stop rushing like that plz. It's no help.

What about the columnization for credits? Is it fine as it is right now, in 1 col?
