### ISSUE TITLE
Accent issue in Safari

### ISSUE THREAD

**Issue by varffs** [interglobalvision/estanciafemsa-mx#13]
In Safari the splash version of CASA LUIS BARRAGÁN nav renders correctly with an accent on the A. However with exactly the same copy in the normal fixed overlay Safari renders CASA LUIS BARRAGAN without an accent!?!?!

**Comment by varffs** [comment]
@mixcas any chance you could look at this?

**Comment by mixcas** [comment]
noup

**Comment by mixcas** [comment]
it's overflowing outside the element. Safari has a default line-height of 21.75px while Chrome's is 24.65px, thats's the difference.

A constant delcared `line-height` should fix it.
![](http://puu.sh/mOH15/1a1b40d640.png)

**Comment by varffs** [comment]
wow thats fucked up tho. Will fix from that tho
