### ISSUE TITLE
<em> italics not working

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#133]
on Home content title

**Comment by mixcas** [comment]
should i switch the field for a wysiwyg then?

**Comment by mikeyrayvon** [comment]
no its not that. its something weird with css

**Comment by mixcas** [comment]
in my local if i input `<em>Somethong</em>` the tags get stripped out

**Comment by mikeyrayvon** [comment]
it doesnt need tags. the `em` is in the markup

**Comment by mikeyrayvon** [comment]
<img width="467" alt="screen shot 2016-09-12 at 7 51 27 pm" src="https://cloud.githubusercontent.com/assets/7727722/18457925/60021b54-7922-11e6-8396-7cc14901fde9.png">
`em` is being overridden by our reset

**Comment by mikeyrayvon** [comment]
i usually set `em` and `strong` in `/site.styl`

**Comment by mixcas** [comment]
that's the reset. then to fix this we should add a class, i think its better than adding `<em>`.

**Comment by mikeyrayvon** [comment]
no because if someone sets italics in post content we want that to work

**Comment by mixcas** [comment]
then the issue is sitewide and not home content specific

**Comment by mikeyrayvon** [comment]
yes

**Comment by mixcas** [comment]
still tho. for elements that use italics as visual aid and not necessarily mean 'emphasis' i think its better to use a class and style that class than adding `<em>`

**Comment by mikeyrayvon** [comment]
but what about post content

**Comment by mikeyrayvon** [comment]
i see what you mean

**Comment by mixcas** [comment]
yes, in post content `<em>` should be used and work

in home content title a class should be used and styled to use italics

theres a semantic diff

**Comment by mikeyrayvon** [comment]
i said i see what you mean

**Comment by mixcas** [comment]
oh, i see it now :)
