### ISSUE TITLE
Missing meta fields on Noticias

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#136]
Author and Date

**Comment by mixcas** [comment]
Only author no? date should be the publish date

**Comment by mikeyrayvon** [comment]
no. its the date that the piece was published. Noticias is press articles

**Comment by mixcas** [comment]
aaahh kk

**Comment by mikeyrayvon** [comment]
we really need to have in-person meetings when we start these projects. because they really dont explain enough
