### ISSUE TITLE
make separate upload forms for Programacion files

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#148]
![screen shot 2016-09-12 at 6 27 55 pm](https://cloud.githubusercontent.com/assets/7727722/18458435/bafd4340-7926-11e6-82e8-ff36fc5d644f.png)

**Comment by mixcas** [comment]
?

**Comment by mixcas** [comment]
u have to wait till the upload is completed 🙃

**Comment by mikeyrayvon** [comment]
i know
