### ISSUE TITLE
Mobile scroll trigger for splash failing

### ISSUE THREAD

**Issue by varffs** [interglobalvision/estanciafemsa-mx#17]
If you attempt to scroll the page it doesn't do enough to trigger out of the initial layout. You have to click the splash to trigger the scroll event to then remove the overlay splash element and let the rest of the page scroll

**Comment by mixcas** [comment]
works fine on android, i think
can u be more descriptive @varffs ?

**Comment by varffs** [comment]
Do we have any ideas on how to solve this? Is there a way to stop any scrolling attempts on mobile and force the trigger of the event that click triggers? [scroll hijack I know @mixcas] or do we find a layout solution for a media query that stops the masked overlay scroll effect and just puts the red box at the top of the scroll?
