### ISSUE TITLE
flex breaking on safari 8

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#204]
<img width="1280" alt="captura de pantalla 2016-09-27 a la s 13 04 17" src="https://cloud.githubusercontent.com/assets/7727722/18929091/9f413b34-8588-11e6-80e1-e9511cc07441.png">

**Comment by varffs** [comment]
woah. tbh I'm not sure we should support Safari 8. Its really old and no longer supported by Apple for security I think

**Comment by mikeyrayvon** [comment]
yea i told them that. its like 0.28% of global usage
