### ISSUE TITLE
search engines should consider estanciafemsa.mx/home as homepage

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/estanciafemsa-mx#212]

**Comment by varffs** [comment]
You mean the first page to open to? I don't think that is possible? Currently this is what a splash page is (and why you shouldn't do them but ...)

**Comment by mikeyrayvon** [comment]
idk what this means. this is something they told me

**Comment by varffs** [comment]
Its not possible then. We just have to tell them that.
