### ISSUE TITLE
Use current_time() instead of time()

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/estanciafemsa-mx#56]
There's a general use of `time()` in this project that was causing me issues, i think we should be using `current_time( 'timestamp' )` instead.

> The local time returned is based on the timezone set on the blog's General Settings page, which is UTC by default.
> 
> current_time( 'timestamp' ) should be used in lieu of time() to return the blog's local time. In WordPress, PHP's time() will always return UTC and is the same as calling current_time( 'timestamp', true ).

**Comment by varffs** [comment]
yh makes sense. change it in your queries branch?
